const ADD_ORDER = "ADD_ORDER";
const DELETE_ORDER = "DELETE_ORDER";
const GET_ORDER_LIST = "GET_ORDER_LIST";
const UPDATE_ORDER_STATUS = "UPDATE_ORDER_STATUS";
const CHANGE_ORDER_VALUE = "CHANGE_ORDER_VALUE";

export default {
    ADD_ORDER,
    DELETE_ORDER,
    GET_ORDER_LIST,
    UPDATE_ORDER_STATUS,
    CHANGE_ORDER_VALUE
}